# Generated by Django 4.2 on 2024-10-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Recruiters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "Id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("details", models.CharField(max_length=255)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Recruiters.recruiter",
                    ),
                ),
            ],
        ),
    ]
