# Generated by Django 4.2 on 2024-10-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Recruiters", "0001_initial"),
        ("Candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "Id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "Id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
                ("workTime", models.CharField(max_length=255, null=True)),
                ("location", models.CharField(max_length=255, null=True)),
                ("salary", models.IntegerField(null=True)),
                (
                    "candidate_application",
                    models.ManyToManyField(
                        related_name="applications",
                        through="JobOffers.Application",
                        to="Candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "Id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Candidates.candidate",
                    ),
                ),
                (
                    "jobOffer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobOffers.joboffer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="joboffer",
            name="candidate_match",
            field=models.ManyToManyField(
                related_name="matches",
                through="JobOffers.Match",
                to="Candidates.candidate",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Recruiters.recruiter"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="jobOffer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="JobOffers.joboffer"
            ),
        ),
    ]
