# Generated by Django 4.2 on 2024-10-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobOffers", "0002_joboffer_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="candidate_Score",
            field=models.IntegerField(null=True),
        ),
    ]
