# Generated by Django 4.2 on 2024-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobOffers", "0003_match_candidate_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="candidate_Score",
        ),
        migrations.AddField(
            model_name="match",
            name="candidate_score",
            field=models.FloatField(null=True),
        ),
    ]
