# Generated by Django 4.2 on 2024-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobOffers", "0004_remove_match_candidate_score_match_candidate_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="candidate_score",
            field=models.FloatField(null=True),
        ),
    ]
