# Generated by Django 4.2 on 2024-11-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobOffers', '0005_application_candidate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='expirationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
