# Generated by Django 4.2 on 2024-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobOffers', '0007_joboffer_company_joboffer_email_joboffer_numtel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
