# Generated by Django 4.2 on 2024-11-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0001_initial'),
        ('JobOffers', '0008_alter_joboffer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recruiters.recruiter'),
        ),
    ]
