# Generated by Django 5.0.6 on 2024-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobOffers', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchedSkills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
