# Generated by Django 4.2 on 2024-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
