# Generated by Django 4.2 on 2024-10-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recruiters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="Id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
