# Generated by Django 4.2 on 2024-11-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0002_recruiter_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='Id',
            new_name='id',
        ),
    ]
