# Generated by Django 4.2 on 2024-11-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0003_rename_id_recruiter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='companyAddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='phoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='post',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
