# Generated by Django 5.0.6 on 2024-11-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0007_alter_notification_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
