# Generated by Django 4.2 on 2024-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0008_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
