# Generated by Django 4.2 on 2024-10-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "Id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="Resumes")),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "Id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "cv",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Candidates.resume",
                    ),
                ),
            ],
        ),
    ]
