# Generated by Django 4.2 on 2024-10-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
