# Generated by Django 4.2 on 2024-10-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="Id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
