# Generated by Django 4.2 on 2024-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_alter_candidate_options_alter_candidate_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='Id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
