# Generated by Django 4.2 on 2024-11-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0004_rename_id_candidate_id_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
    ]
