# Generated by Django 4.2 on 2024-11-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0006_alter_candidate_options_alter_candidate_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='username',
            new_name='name',
        ),
    ]
