# Generated by Django 4.2 on 2024-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0007_rename_username_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dateOfBirth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
