# Generated by Django 4.2 on 2024-11-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0008_candidate_adress_candidate_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='adress',
            new_name='address',
        ),
    ]
