# Generated by Django 4.2 on 2024-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0009_rename_adress_candidate_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='act_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='act_mob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='act_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='cand_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='courses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='dev_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='host_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ip_add',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='latlong',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='no_of_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='os_name_ver',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='reco_field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='res_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='sec_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
