# Generated by Django 4.2 on 2024-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0010_remove_resume_file_resume_act_mail_resume_act_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cand_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='latlong',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='no_of_pages',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='res_score',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
