# Generated by Django 4.2 on 2024-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0011_alter_resume_cand_level_alter_resume_latlong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommended_skills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
