# Generated by Django 4.2 on 2024-11-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0012_resume_recommended_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
