# Generated by Django 4.2 on 2024-11-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0013_candidate_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
    ]
