# Generated by Django 4.2 on 2024-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0014_remove_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
