# Generated by Django 4.2 on 2024-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0016_alter_candidate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
