# Generated by Django 4.2 on 2024-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0017_alter_resume_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
