# Generated by Django 4.2 on 2024-11-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0019_remove_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidates.resume'),
        ),
    ]
